### ISSUE TITLE
Regarding Eden Plus Mosiac

### ISSUE THREAD

**Issue by Cosetto** [imKota/fuckpaz#1]
Do you know how to set the encode back to shift-jis or utf8? My language has 134 special characters so I need to use custom font to display it, so I decided to replace it with hiragana and katakana but the game doesn't display them, only half width katakana displays.
[eden_pm_en.zip](https://github.com/imKota/fuckpaz/files/7531885/eden_pm_en.zip)
Here is the exe

**Comment by imKota** [comment]
@Cosetto you ned use [this](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp) patch. Or just use Japanese version game.

**Comment by imKota** [comment]
@Cosetto In what language is the translation planned?

**Comment by Cosetto** [comment]
> @Cosetto In what language is the translation planned?

Vietnamese

**Comment by imKota** [comment]
> > @Cosetto In what language is the translation planned?
> 
> Vietnamese

Give me your discord id
